### ISSUE TITLE
Feature request - Sort by number of tabs

### ISSUE THREAD

**Issue by macta** [plsankar/tabcloserpro#64]
It would be handy to sort the list of tabs to close by number of instances vs alphabetically - as I like this extension to help me close a list of LinkedIn windows I've accumulated.

**Comment by plsankar** [comment]
Hey @macta,

Thanks for the feature request. It is a good one. will add it.

Sorry for the late response.

**Comment by plsankar** [comment]
Hey @macta,

The feature has been requested added and the new version is available now.

Thanks for the suggestion.

**Comment by macta** [comment]
Hi - this is nice and much appreciated as it definitely makes it easier to manage tabs.

2 minor things to add -
1. Grammatically it would be better to sort by "Tab Count" (without an 's' - minor comment)
2. It would be nice if it would save which sort mechanism I am using, as each time I pick the extension I have to set it back to sort by Tab Count again

Thanks again for improving the extension - I know these are a labour of love.

**Comment by plsankar** [comment]
Hi, 

Yep, the saving the filter makes sense. 

I have made the changes and published a newer version, should be available soon.

Thanks for suggestion.
